version: '2'
services:
    liutianhong-app:
        image: liutianhong
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://liutianhong-mysql:3306/liutianhong?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    liutianhong-mysql:
        extends:
            file: mysql.yml
            service: liutianhong-mysql
